### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [arkadiusz-cichosz/tables#1]
- [x] środowisko uruchomieniowe?
- [x] spacje
- [x] niepotrzebny `else`
- [x] przydałby się jakiś `console.log` do podglądu tych tablic

**Comment by arkadiusz-cichosz** [comment]
Srodowisko: node

**Comment by arkadiusz-cichosz** [comment]
Dodałem wyświetlenie zawartości tablicy po wszystkich operacjach
